[package]
name = "example"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
embedded-hal = "1.0.0"
embedded-hal-bus = "0.3.0"
is31fl3743b-driver = { version = "0.1.0", features = [ "is_blocking" ]}
pico-de-gallo = { path = "../library" }
shtcx = "1.0.0"
