[package]
name = "pico-de-gallo-ffi"
version = "0.2.1"
edition = "2024"

[dependencies]
futures = "0.3.31"
pico-de-gallo-lib = { path = "../pico-de-gallo-lib" }

[build-dependencies]
cbindgen = "0.29"

[lib]
crate-type = ["cdylib"]
