[package]
name = "pico-de-gallo"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
embedded-hal = "1.0.0"
nusb = "0.2.0"
thiserror = "2.0.16"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
