[package]
name = "pico-de-gallo-internal"
version = "0.2.0"
edition = "2024"

[dependencies]
defmt = { version = "1.0.1", optional = true }
serde = { version = "1.0.219", default-features = false, features = ["derive"] }

[features]
defmt = ["dep:defmt"]
