[package]
name = "pico-de-gallo-internal"
version = "0.3.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", default-features = false, features = ["derive"] }
postcard-rpc = "0.11"
postcard-schema = { version = "0.2.5", features = ["derive"] }

[features]
use-std = []
